### ISSUE TITLE
Power switch and shutter button

### ISSUE THREAD

**Issue by mikecheng2626** [penk/ruha.camera#5]
Hi,

What kind of power switch and shutter button are they? Just trying to make sure my grocery list is the same.

**Comment by penk** [comment]
Hi, I use the spare parts I had at hand, but I believe anything works -- as long as you can tweak the shape on printed parts so it fits. 

Amazon link attached for reference: 
https://www.amazon.co.jp/dp/B01LYVYQNO
https://www.amazon.co.jp/dp/B0822GHZ36
