### ISSUE TITLE
Link to display? 

### ISSUE THREAD

**Issue by btilford** [penk/ruha.camera#6]
Most displays I've found are 2.8" 

Also, are some of these parts like the top glued together? The mount looks like it has structure for screws that line up with the main body but, there aren't guide holes.

**Comment by penk** [comment]
Hi, 

Here's one of those 2.2 TFT I found on Amazon, no affiliation: http://amazon.com/dp/B01CZL6QIQ 
All 3D parts are glued; HQ camera and Pi Zero can be screwed into place (or using hot glue if needed). 

![](https://i.imgur.com/InPryr3.jpg)
