### ISSUE TITLE
TFT Display Driver

### ISSUE THREAD

**Issue by nishabe** [penk/ruha.camera#9]
I have this display: http://amazon.com/dp/B01CZL6QIQ
However, I have difficulties in making it work.

Could you please share which driver you have used?
Any link to the steps much appreciated.
@penk

**Comment by RadiantFeline** [comment]
I'm using the same board with this https://github.com/juj/fbcp-ili9341

**Comment by penk** [comment]
Hi, I'm simply using the rpi-display dtoverlay, (`dtoverlay=rpi-display` in `config.txt`). 
Source: 
https://github.com/raspberrypi/linux/blob/rpi-5.10.y/arch/arm/boot/dts/overlays/rpi-display-overlay.dts

I find this post very helpful: 
https://tejaswid.github.io/wikitm/rpi/pi-tft-display
